<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "chapted_page"
 *
 * Auto generated by Extension Builder 2017-02-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'One Pager',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Michael Blunck, Mirco Winkler',
	'author_email' => 'mi.blunck@gmail.com, mirco.winkler@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);